#!/usr/bin/env bash
# manages 'manage_my_process'

file1="/var/run/my_process.pid"
file2="manage_my_process"

starts_creates_func()
{
    ./"$file2" &
    touch "$file1"
    echo "$!" > "$file1"
}

stops_func()
{
    kill $(cat "$file1")
}

displays_func()
{
    case $1 in
    start)
        echo "manage_my_process started";;
    stop)
        echo "manage_my_process stopped";;
    restart)
        echo "manage_my_process restarted";;
    esac
}

deletes_func()
{
    rm "$file1"
}


if [ $# -ne 1 ]
then
    echo "Usage: manage_my_process {start|stop|restart}"
else
    case $1 in
    start)
        #start the process
        starts_creates_func
        displays_func "start"
        ;;
    stop)
        #stop the process
        stops_func
        deletes_func
        displays_func "stop"
        ;;
    restart)
        # restart the process
        stops_func
        deletes_func
        starts_creates_func
        displays_func "restart"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
    esac
fi
