#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# displays only username, user id, and home directory path for the user.

file="/etc/passwd"

while read -r line;
do
    echo "$line" | cut -d':' -f1,3,6
done < "$file"
