#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS. 

IFS=':'

while read -r username passwd user_id group_id user_id_info home_directory shell;
do
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell."
    echo "$user_id's place is protected by the passcode $passwd, more info about the user here: $user_id_info"
done < /etc/passwd
