#!/usr/bin/env bash
# configures an Ubuntu server

# creates a backup
cp /etc/hosts /etc/hosts.old
# replace 127.0.0.1 with 127.0.0.2 in /etc/hosts
sed -i s/127.0.0.1/127.0.0.2/ /etc/hosts
# append "8.8.8.8    facebook.com" to /etc/hosts
echo "8.8.8.8    facebook.com" >> /etc/hosts
